// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opztejwswutanebehrgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wenRlandzd3V0YW5lYmVocmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzg4NTYsImV4cCI6MjA1OTQ1NDg1Nn0.koEcDyRpMl-_-tAApDIzq0he2RkwyCPkSxSKhzyrvxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);